version: "3.5"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: next-dockerized
        ports:
            - "3000:3000"
        volumes:
            - './files:/app/files'
