version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: nextjs
        ports:
            - "3000:3000"
        volumes:
            - "./files:/app/files"
        restart: always
